### PR TITLE
Update jupyter-server and nbclassic dependencies to remove error on launch

### PR DESCRIPTION
**Pull request by tmckayus**
## Related Issues and Dependencies

…

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

The notebook fails on launch with 

"AttributeError: 'ExtensionManager' object has no attribute '_extensions'"

This is because of recent changes in jupyter-server and/or nbclassic. Updating the deps fixes the issue.

### CODE REVIEW

**Comment by tmckayus** [comment]
@vpavlin @harshad16 ptal

An OpenShift build using the updatedeps branch (source of this PR) produces a notebook image which launches from jupyterhub without the error

```
  source:
    git:
      ref: updatedeps
      uri: https://github.com/red-hat-data-services/s2i-pytorch-notebook
    type: Git
```

**Comment by vpavlin** [comment]
lgtm

**Review by harshad16 — APPROVED** [review]

**Pull request merged**
